"""
app.py — FastAPI web application for LEO satellite risk analysis.

Provides a local interactive map with:
  • Esri World Imagery satellite tile background (via Leaflet.js)
  • Pre-computed risk results as clickable markers (popup with 5-panel PNG)
  • Click-anywhere → nearest DATA_CHALLENGE_50 point lookup → on-demand analysis
  • Leaflet.Draw rectangle → AOI batch analysis (100-point confirmation gate)

Usage:
    conda run -n cs378 uvicorn app:app --reload --port 8000
    # Then open http://localhost:8000 in a browser

Design:
    - Analysis runs asynchronously: endpoints return a job_id immediately (HTTP 202)
      and the client polls GET /api/status/{job_id} until status == "done" | "error".
    - Analysis work runs in a thread pool (ThreadPoolExecutor) so it does not block
      the asyncio event loop — the server remains responsive during long analyses.
    - Pre-computed results served from challenge50 + nc_test JSON files
    - Nearest-point lookup uses vectorised numpy distance (no spatial index needed
      for <5M points once loaded; first request cold-loads the CSV in ~5s)
    - PNGs are generated by _plot_point() from main.py (same as CLI)
    - Structured for future deployment: replace localhost uvicorn with gunicorn,
      add auth middleware, swap local PNG serve with S3 presigned URLs

Endpoints:
    GET  /                        — interactive map HTML
    GET  /api/precomputed         — all pre-computed results (JSON)
    POST /api/analyze             — single-point on-demand analysis (async, returns job_id)
    GET  /api/status/{job_id}     — poll job status / retrieve result
    POST /api/analyze_bbox        — batch analysis for a drawn bounding box (async)
    GET  /api/nearest             — nearest DATA_CHALLENGE_50 point lookup
    GET  /outputs/{path:path}     — serve PNG / JSON files from outputs/
"""

from __future__ import annotations

import asyncio
import base64
import io
import json
import logging
import sys
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
ROOT     = Path(__file__).parent
SRC_DIR  = ROOT / "src"
OUT_DIR  = ROOT / "outputs"
TMPL_DIR = ROOT / "templates"

sys.path.insert(0, str(SRC_DIR))

from feasibility import analyze_location
import main as _main_mod   # for _plot_point, _save_json

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------
app = FastAPI(title="LEO Risk Analysis", version="1.0.0")
app.mount("/outputs", StaticFiles(directory=str(OUT_DIR)), name="outputs")
templates = Jinja2Templates(directory=str(TMPL_DIR))

# ---------------------------------------------------------------------------
# In-memory state (loaded once on first use)
# ---------------------------------------------------------------------------
_challenge_df: pd.DataFrame | None = None   # 4.67M NC addresses (lazy)
_precomputed:  list[dict]  | None = None    # challenge50 + nc_test results
_sample_cache: list[dict]  | None = None    # 20K stratified sample for map display (legacy)

# Async job store: job_id → {status, result?, error?, ...}
_jobs: dict[str, dict] = {}

# Thread pool for CPU/network-bound analysis work (keeps asyncio loop unblocked)
_analysis_pool = ThreadPoolExecutor(max_workers=3, thread_name_prefix="analysis")

AOI_CONFIRMATION_THRESHOLD = 100   # Points above this require explicit confirm
MAP_SAMPLE_SIZE = 20_000           # Points to show as gray dots on the map
VIEWPORT_MAX_POINTS = 5_000        # Max unanalyzed dots per viewport request


def _load_challenge_df() -> pd.DataFrame:
    global _challenge_df
    if _challenge_df is None:
        csv = ROOT / "DATA_CHALLENGE_50.csv"
        logger.info(f"Loading {csv.name} …")
        _challenge_df = pd.read_csv(csv, usecols=["location_id", "latitude", "longitude", "geoid_cb"],
                                    dtype={"location_id": str, "geoid_cb": str})
        logger.info(f"Loaded {len(_challenge_df):,} addresses")
    return _challenge_df


def _load_precomputed() -> list[dict]:
    """Load ALL analyzed points from every source into a unified, deduplicated list.

    Priority (later source wins on duplicate location_id):
      1. challenge50 CSV
      2. nc_test JSONs
      3. batch_results CSV
      4. on-demand reports/ JSONs  (highest priority — most recent)
    """
    global _precomputed
    if _precomputed is not None:
        return _precomputed

    by_id: dict[str, dict] = {}  # location_id → row (later insert wins)

    def _norm(row: dict, source: str) -> dict:
        row["_source"] = source
        lid = str(row.get("location_id", ""))
        row["location_id"] = lid
        return row

    # 1. Challenge-50 results
    c50_csv = OUT_DIR / "challenge50" / "challenge50_results.csv"
    if c50_csv.exists():
        df = pd.read_csv(c50_csv)
        for col in ("risk_score", "slope_deg", "canopy_max_m", "building_count"):
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)
        if "feasible" in df.columns:
            df["feasible"] = (df["feasible"].astype(str).str.lower()
                              .map({"true": True, "false": False, "1": True, "0": False})
                              .fillna(True))
        for r in df.to_dict("records"):
            r = _norm(r, "challenge50")
            by_id[r["location_id"]] = r

    # 2. NC test set (per-point JSONs)
    nc_dir = OUT_DIR / "nc_test"
    for jf in sorted(nc_dir.glob("point_*.json")):
        try:
            d = json.loads(jf.read_text())
            rk = d.get("risk", {})
            cl = d.get("classification", {})
            lid = jf.stem.replace("point_", "")
            by_id[lid] = _norm({
                "location_id": lid, "lat": d.get("lat"), "lon": d.get("lon"),
                "latitude": d.get("lat"), "longitude": d.get("lon"),
                "feasible": d.get("feasible", True),
                "risk_score": rk.get("risk_score", 0), "risk_tier": rk.get("risk_tier", "low"),
                "dominant": cl.get("dominant", "clear"), "slope_deg": d.get("slope_deg", 0),
                "canopy_max_m": d.get("canopy_max_m", 0), "building_count": d.get("building_count", 0),
                "warnings": "; ".join(d.get("warnings", [])),
            }, "nc_test")
        except Exception:
            pass

    # 3. Full batch results
    batch_csv = OUT_DIR / "batch" / "batch_results.csv"
    if batch_csv.exists():
        bdf = pd.read_csv(batch_csv)
        if "error" in bdf.columns:
            bdf = bdf[bdf["error"].isna()]
        for col in ("risk_score", "slope_deg", "canopy_max_m", "building_count"):
            if col in bdf.columns:
                bdf[col] = pd.to_numeric(bdf[col], errors="coerce").fillna(0)
        if "feasible" in bdf.columns:
            bdf["feasible"] = (bdf["feasible"].astype(str).str.lower()
                               .map({"true": True, "false": False}).fillna(True))
        for r in bdf.to_dict("records"):
            r = _norm(r, "batch")
            by_id[r["location_id"]] = r

    # 4. On-demand reports (highest priority — freshest data with PNGs)
    reports_dir = OUT_DIR / "reports"
    if reports_dir.exists():
        for jf in sorted(reports_dir.glob("*/*.json")):
            try:
                d = json.loads(jf.read_text())
                lid = jf.parent.name
                rk = d.get("risk", {})
                cl = d.get("classification", {})
                by_id[lid] = _norm({
                    "location_id": lid, "lat": d.get("lat"), "lon": d.get("lon"),
                    "latitude": d.get("lat"), "longitude": d.get("lon"),
                    "feasible": d.get("feasible", True),
                    "risk_score": rk.get("risk_score", 0), "risk_tier": rk.get("risk_tier", "low"),
                    "dominant": cl.get("dominant", "clear"), "slope_deg": d.get("slope_deg", 0),
                    "canopy_max_m": d.get("canopy_max_m", 0), "building_count": d.get("building_count", 0),
                    "failure_mode": d.get("failure_mode", ""),
                    "warnings": "; ".join(d.get("warnings", [])),
                }, "on_demand")
            except Exception:
                pass

    _precomputed = list(by_id.values())
    logger.info(f"Loaded {len(_precomputed)} unique pre-computed results")
    return _precomputed


# ---------------------------------------------------------------------------
# Request/response models
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    lat: float
    lon: float
    location_id: str = "on-demand"
    run_search:  bool = True


class BboxRequest(BaseModel):
    lat_min: float
    lat_max: float
    lon_min: float
    lon_max: float
    confirmed: bool = False   # True = user already clicked "Run anyway" for >100 pts


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _nearest_challenge_point(lat: float, lon: float) -> dict | None:
    """Return the nearest DATA_CHALLENGE_50 point to (lat, lon)."""
    df = _load_challenge_df()
    dlat = df["latitude"].values  - lat
    dlon = df["longitude"].values - lon
    dist = dlat**2 + dlon**2
    idx  = int(np.argmin(dist))
    row  = df.iloc[idx]
    return {
        "location_id": str(row["location_id"]),
        "lat":         float(row["latitude"]),
        "lon":         float(row["longitude"]),
        "dist_m":      float(np.sqrt(dist[idx]) * 111_320),
    }


PANEL_NAMES = ["terrain", "canopy_buildings", "constraints", "horizon", "neighborhood"]
PANEL_TITLES = ["Terrain (far-field)", "Canopy + Buildings", "Constraints", "Horizon Profile", "Neighbourhood"]


def _get_panel_urls(lid: str) -> list[dict] | None:
    """Return list of individual panel image URLs if they exist."""
    report_dir = OUT_DIR / "reports" / lid
    if not report_dir.exists():
        return None
    panels = []
    for name, title in zip(PANEL_NAMES, PANEL_TITLES):
        p = report_dir / f"panel_{name}.png"
        if p.exists():
            panels.append({"name": name, "title": title, "url": f"/outputs/reports/{lid}/panel_{name}.png"})
    return panels if panels else None


def _split_combined_png(lid: str):
    """Crop-split a combined 5-panel PNG into individual panels (fallback).

    Used only for legacy points that have a combined PNG but no individual panels.
    New analyses generate proper individual panels via _save_individual_panels().
    """
    report_dir = OUT_DIR / "reports" / lid
    combined = report_dir / f"{lid}.png"
    if not combined.exists():
        return
    if (report_dir / f"panel_{PANEL_NAMES[0]}.png").exists():
        return  # already has panels
    try:
        from PIL import Image
        img = Image.open(combined)
        w, h = img.size
        pw = w // 5
        for i, name in enumerate(PANEL_NAMES):
            x0 = i * pw
            x1 = (i + 1) * pw if i < 4 else w
            panel = img.crop((x0, 0, x1, h))
            panel.save(report_dir / f"panel_{name}.png", optimize=True)
    except Exception as exc:
        logger.warning(f"Panel split failed for {lid}: {exc}")


def _png_b64(result: dict, location_id: str) -> str:
    """Generate a 5-panel PNG for result and return as base64 string."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    result["label"] = location_id
    buf = io.BytesIO()
    try:
        fig_path = OUT_DIR / "reports" / location_id / f"{location_id}.png"
        fig_path.parent.mkdir(parents=True, exist_ok=True)
        _main_mod._plot_point(result, fig_path)
        png_bytes = fig_path.read_bytes()
    except Exception as exc:
        logger.warning(f"Plot failed: {exc}")
        return ""
    return base64.b64encode(png_bytes).decode()


def _save_analysis_result(result: dict, location_id: str):
    """Persist JSON + PNG + split panels for a completed analysis result."""
    json_path = OUT_DIR / "reports" / location_id / f"{location_id}.json"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    _main_mod._save_json(result, json_path)
    _png_b64(result, location_id)
    _split_combined_png(location_id)


async def _run_analysis_job(job_id: str, lat: float, lon: float,
                             location_id: str, run_search: bool):
    """Background coroutine: run analyze_location in the thread pool, store result."""
    loop = asyncio.get_event_loop()
    t0   = time.time()
    try:
        result = await loop.run_in_executor(
            _analysis_pool,
            lambda: analyze_location(lat, lon, run_local_search=run_search),
        )
        await loop.run_in_executor(
            _analysis_pool,
            lambda: _save_analysis_result(result, location_id),
        )
        api_result = _result_to_api(result, location_id)
        api_result["total_elapsed_s"] = round(time.time() - t0, 1)
        _jobs[job_id] = {"status": "done", "result": api_result}
        global _precomputed, _sample_cache
        _precomputed = None
        _sample_cache = None
        logger.info(f"[job:{job_id}] done in {time.time()-t0:.1f}s")
    except Exception as exc:
        logger.error(f"[job:{job_id}] failed: {exc}")
        _jobs[job_id] = {"status": "error", "error": str(exc)}


async def _run_bbox_job(job_id: str, subset: pd.DataFrame):
    """Background coroutine: run bbox batch analysis point-by-point in thread pool."""
    loop     = asyncio.get_event_loop()
    n        = len(subset)
    results_out: list[dict] = []
    errors:      list[dict] = []

    for i, (_, row) in enumerate(subset.iterrows(), 1):
        lid = str(row["location_id"])
        _jobs[job_id]["completed"] = i - 1
        try:
            res = await loop.run_in_executor(
                _analysis_pool,
                lambda r=row: analyze_location(
                    float(r["latitude"]), float(r["longitude"]), run_local_search=False
                ),
            )
            await loop.run_in_executor(
                _analysis_pool,
                lambda r=res, l=lid: _save_analysis_result(r, l),
            )
            results_out.append(_result_to_api(res, lid, source="aoi_batch"))
        except Exception as exc:
            errors.append({"location_id": lid, "error": str(exc)})

    _jobs[job_id].update({
        "status":   "done",
        "completed": n,
        "results":  results_out,
        "errors":   errors,
        "n_points": n,
    })
    global _precomputed, _sample_cache
    _precomputed = None
    _sample_cache = None
    logger.info(f"[bbox_job:{job_id}] done — {len(results_out)}/{n} ok, {len(errors)} errors")


def _result_to_api(result: dict, location_id: str, source: str = "on-demand") -> dict:
    """Strip numpy arrays and add API-friendly fields."""
    rk  = result.get("risk", {})
    cl  = result.get("classification", {})
    bn  = result.get("best_nearby") or {}
    imp = bn.get("improvement") or {}
    return {
        "location_id":    location_id,
        "lat":            result["lat"],
        "lon":            result["lon"],
        "feasible":       result["feasible"],
        "failure_mode":   result.get("failure_mode", ""),
        "risk_score":     rk.get("risk_score", 0),
        "risk_tier":      rk.get("risk_tier", "low"),
        "dominant":       cl.get("dominant", "clear"),
        "slope_deg":      result.get("slope_deg", 0),
        "canopy_max_m":   result.get("canopy_max_m", 0),
        "building_count": result.get("building_count", 0),
        "warnings":       "; ".join(result.get("warnings", [])),
        "elapsed_s":      result.get("elapsed_s", 0),
        "best_nearby": {
            "lat":        bn.get("best", {}).get("lat") if bn.get("best") else None,
            "lon":        bn.get("best", {}).get("lon") if bn.get("best") else None,
            "risk_score": bn.get("best", {}).get("risk_score") if bn.get("best") else None,
            "distance_m": imp.get("distance_m"),
            "risk_delta": imp.get("risk_delta"),
            "feasible_gained": imp.get("feasible_gained"),
        } if bn else None,
        "_source":        source,
        "png_url":        f"/outputs/reports/{location_id}/{location_id}.png",
        "panels":         _get_panel_urls(location_id),
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    precomputed = _load_precomputed()
    df = _load_challenge_df()
    return templates.TemplateResponse("map.html", {
        "request":       request,
        "n_precomputed": len(precomputed),
        "n_total":       len(df),
    })


@app.get("/api/precomputed")
async def get_precomputed():
    rows = _load_precomputed()
    # Ensure lat/lon present from either column naming convention
    out = []
    seen = set()
    for r in rows:
        lat = r.get("lat") or r.get("latitude")
        lon = r.get("lon") or r.get("longitude")
        if lat is None or lon is None:
            continue
        lid = str(r.get("location_id", ""))
        if lid in seen:
            continue
        seen.add(lid)
        out.append({
            "location_id":    lid,
            "lat":            float(lat),
            "lon":            float(lon),
            "feasible":       bool(r.get("feasible", True)),
            "risk_score":     float(r.get("risk_score", 0)),
            "risk_tier":      str(r.get("risk_tier", "low")),
            "dominant":       str(r.get("dominant", "clear")),
            "slope_deg":      float(r.get("slope_deg", 0)),
            "canopy_max_m":   float(r.get("canopy_max_m", 0)),
            "building_count": int(r.get("building_count", 0)),
            "warnings":       str(r.get("warnings", "") or ""),
            "_source":        str(r.get("_source", "")),
            "png_url":        f"/outputs/reports/{lid}/{lid}.png" if (OUT_DIR / "reports" / lid / f"{lid}.png").exists() else None,
            "panels":         _get_panel_urls(lid),
        })
    return JSONResponse(content=out)


@app.post("/api/reload")
async def reload_precomputed():
    """Force-reload all pre-computed results from disk (challenge50, nc_test, batch CSVs).

    Use after a batch run completes externally, or after manually replacing a CSV,
    to pick up new data without restarting the server.
    """
    global _precomputed, _sample_cache
    _precomputed = None
    _sample_cache = None
    rows = _load_precomputed()
    logger.info(f"[api/reload] Reloaded {len(rows)} pre-computed results from disk")
    return JSONResponse(content={"status": "ok", "n_results": len(rows)})


@app.post("/api/update_zonal")
async def update_zonal():
    """Recompute county + block group zonal summaries from ALL analyzed points.

    Joins analyzed results with the full dataset (via geoid_cb) to assign each
    analyzed point to a county and block group, then aggregates pass rate and
    risk statistics. Invalidates the choropleth caches so the next fetch picks
    up the new data.
    """
    global _bg_geojson_cache, _county_geojson_cache

    precomputed = _load_precomputed()
    df_full = _load_challenge_df()

    # Build analyzed DataFrame
    rows = []
    for r in precomputed:
        lat = r.get("lat") or r.get("latitude")
        lon = r.get("lon") or r.get("longitude")
        if lat is None or lon is None:
            continue
        rows.append({
            "location_id": str(r.get("location_id", "")),
            "lat": float(lat),
            "lon": float(lon),
            "feasible": bool(r.get("feasible", True)),
            "risk_score": float(r.get("risk_score", 0)),
            "risk_tier": str(r.get("risk_tier", "low")),
            "dominant": str(r.get("dominant", "clear")),
        })

    if not rows:
        return JSONResponse(content={"status": "error", "message": "No analyzed points"})

    adf = pd.DataFrame(rows)
    adf["location_id"] = adf["location_id"].astype(str)

    # Join with full dataset to get geoid_cb
    df_full["location_id"] = df_full["location_id"].astype(str)
    merged = adf.merge(
        df_full[["location_id", "geoid_cb"]],
        on="location_id", how="left",
    )

    # Derive county_fips (first 5 digits) and block_group (first 12 digits)
    merged["geoid_cb"] = merged["geoid_cb"].astype(str)
    merged["county_fips"] = merged["geoid_cb"].str[:5]
    merged["geoid_bg"] = merged["geoid_cb"].str[:12]

    # Filter out rows without valid geoid
    merged = merged[merged["geoid_cb"].str.len() >= 12]

    def _summarize(group_col: str) -> pd.DataFrame:
        g = merged.groupby(group_col)
        summary = g.agg(
            n_points=("risk_score", "size"),
            mean_risk=("risk_score", "mean"),
            median_risk=("risk_score", "median"),
            n_feasible=("feasible", "sum"),
        ).reset_index()
        summary["pct_feasible"] = (summary["n_feasible"] / summary["n_points"] * 100).round(1)
        summary["n_infeasible"] = summary["n_points"] - summary["n_feasible"]

        # Tier percentages
        for tier in ["low", "moderate", "high", "critical"]:
            tier_counts = merged[merged["risk_tier"] == tier].groupby(group_col).size()
            summary[f"pct_{tier}"] = (tier_counts.reindex(summary[group_col]).fillna(0).values
                                      / summary["n_points"] * 100).round(1)

        # Dominant mode
        dom_mode = merged.groupby(group_col)["dominant"].agg(
            lambda x: x.value_counts().index[0] if len(x) > 0 else "clear"
        )
        summary["dominant_mode"] = dom_mode.reindex(summary[group_col]).values

        summary["mean_risk"] = summary["mean_risk"].round(1)
        summary["median_risk"] = summary["median_risk"].round(1)
        return summary

    # County summary
    county_summary = _summarize("county_fips")
    county_csv = OUT_DIR / "zonal" / "county_summary.csv"
    county_csv.parent.mkdir(parents=True, exist_ok=True)
    county_summary.to_csv(county_csv, index=False)

    # Block group summary
    bg_summary = _summarize("geoid_bg")
    bg_csv = OUT_DIR / "zonal" / "block_group_summary.csv"
    bg_summary.to_csv(bg_csv, index=False)

    # Invalidate choropleth caches
    _bg_geojson_cache = None
    _county_geojson_cache = None

    n_counties = len(county_summary)
    n_bgs = len(bg_summary)
    logger.info(f"[update_zonal] Updated: {n_counties} counties, {n_bgs} block groups from {len(merged)} points")

    return JSONResponse(content={
        "status": "ok",
        "n_analyzed": len(merged),
        "n_counties": n_counties,
        "n_block_groups": n_bgs,
    })


@app.get("/api/all_points")
async def all_points():
    """Return a stratified 20K sample of ALL dataset points for map display.

    Each point includes: location_id, lat, lon, and whether it has been analyzed.
    Pre-computed points include their risk_tier so the frontend can color them.
    Unanalyzed points are shown as gray dots that can be clicked to compute.
    """
    global _sample_cache
    if _sample_cache is None:
        df = _load_challenge_df()
        precomputed = _load_precomputed()

        # Build set of analyzed location_ids
        analyzed_ids = set()
        analyzed_map = {}  # location_id → {risk_tier, risk_score, feasible, ...}
        for r in precomputed:
            lid = str(r.get("location_id", ""))
            analyzed_ids.add(lid)
            analyzed_map[lid] = r

        # Stratified sample: take ~20K points spread across all counties
        sample = df.sample(min(MAP_SAMPLE_SIZE, len(df)), random_state=42)

        # Ensure ALL analyzed points are included (even if not in random sample)
        analyzed_lids_in_sample = set(sample["location_id"].astype(str)) & analyzed_ids
        missing_analyzed = analyzed_ids - analyzed_lids_in_sample
        if missing_analyzed:
            extras = df[df["location_id"].astype(str).isin(missing_analyzed)]
            sample = pd.concat([sample, extras], ignore_index=True).drop_duplicates(
                subset="location_id", keep="first"
            )

        rows = []
        for _, r in sample.iterrows():
            lid = str(r["location_id"])
            if lid in analyzed_map:
                am = analyzed_map[lid]
                lat = am.get("lat") or am.get("latitude")
                lon = am.get("lon") or am.get("longitude")
                rows.append({
                    "i": lid,
                    "a": round(float(lat), 5),
                    "o": round(float(lon), 5),
                    "z": 1,  # analyzed
                    "t": str(am.get("risk_tier", "low")),
                    "f": bool(am.get("feasible", True)),
                    "s": round(float(am.get("risk_score", 0)), 1),
                })
            else:
                rows.append({
                    "i": lid,
                    "a": round(float(r["latitude"]), 5),
                    "o": round(float(r["longitude"]), 5),
                    "z": 0,  # not analyzed
                })

        _sample_cache = rows
        logger.info(f"[api/all_points] Built sample: {len(rows)} pts "
                    f"({sum(1 for r in rows if r['z'])} analyzed)")

    return JSONResponse(content=_sample_cache)


@app.post("/api/analyze")
async def analyze(req: AnalyzeRequest):
    """
    On-demand single-point analysis — returns a job_id immediately (HTTP 202).

    The client should poll GET /api/status/{job_id} until status == "done" or "error".
    Analysis runs in a background thread so the event loop stays unblocked.
    """
    logger.info(f"[api/analyze] lat={req.lat:.5f} lon={req.lon:.5f} id={req.location_id}")
    job_id = uuid.uuid4().hex[:12]
    _jobs[job_id] = {"status": "pending", "location_id": req.location_id,
                     "lat": req.lat, "lon": req.lon}
    asyncio.create_task(
        _run_analysis_job(job_id, req.lat, req.lon, req.location_id, req.run_search)
    )
    return JSONResponse(
        status_code=202,
        content={"job_id": job_id, "status": "pending", "location_id": req.location_id},
    )


@app.get("/api/status/{job_id}")
async def job_status(job_id: str):
    """
    Poll the status of a background analysis job.

    Returns:
        pending  — job is queued or running
        done     — job complete; "result" key holds the analysis output
        error    — job failed; "error" key holds the exception message
    """
    job = _jobs.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
    return JSONResponse(content=job)


@app.get("/api/nearest")
async def nearest(lat: float, lon: float):
    """Return the nearest DATA_CHALLENGE_50 point to (lat, lon)."""
    pt = _nearest_challenge_point(lat, lon)
    if pt is None:
        raise HTTPException(status_code=404, detail="Dataset not available")
    return JSONResponse(content=pt)


@app.post("/api/analyze_bbox")
async def analyze_bbox(req: BboxRequest):
    """
    Batch analysis for an AOI bounding box drawn on the map.

    Flow:
      1. If bbox > threshold and confirmed=False → return confirmation_required (200, not 202)
         so the frontend can show a dialog, then re-submit with confirmed=True.
      2. Otherwise → start async job, return job_id immediately (HTTP 202 with status="running").
      3. Client polls GET /api/status/{job_id}; the job dict includes "completed" / "total"
         for live progress display.
    """
    df = _load_challenge_df()
    mask = (
        (df["latitude"]  >= req.lat_min) & (df["latitude"]  <= req.lat_max) &
        (df["longitude"] >= req.lon_min) & (df["longitude"] <= req.lon_max)
    )
    subset = df[mask].copy()
    n = len(subset)

    if n == 0:
        return JSONResponse(content={"status": "empty", "n_points": 0, "results": []})

    if n > AOI_CONFIRMATION_THRESHOLD and not req.confirmed:
        # Use HTTP 200 so the frontend can inspect status field without re-parsing 202
        return JSONResponse(
            status_code=200,
            content={
                "status":    "confirmation_required",
                "n_points":  n,
                "threshold": AOI_CONFIRMATION_THRESHOLD,
                "message":   (
                    f"This AOI contains {n:,} points (~{n * 30 // 60} min). "
                    f"Re-submit with confirmed=true to proceed."
                ),
            },
        )

    # Cap to threshold
    if n > AOI_CONFIRMATION_THRESHOLD:
        subset = subset.sample(AOI_CONFIRMATION_THRESHOLD, random_state=42)
        n = AOI_CONFIRMATION_THRESHOLD
        logger.info(f"[api/analyze_bbox] Sampled {AOI_CONFIRMATION_THRESHOLD} pts")

    job_id = uuid.uuid4().hex[:12]
    _jobs[job_id] = {"status": "running", "total": n, "completed": 0}
    logger.info(f"[api/analyze_bbox] job={job_id} n={n}")
    asyncio.create_task(_run_bbox_job(job_id, subset))

    return JSONResponse(
        status_code=202,
        content={"job_id": job_id, "status": "running", "n_points": n},
    )


# ---------------------------------------------------------------------------
# Viewport-based point loading (progressive zoom)
# ---------------------------------------------------------------------------

@app.get("/api/points_in_view")
async def points_in_view(lat_min: float, lat_max: float, lon_min: float, lon_max: float):
    """Return points within the visible map viewport.

    Returns analyzed points (colored) + a capped sample of unanalyzed points (white).
    Used at high zoom levels instead of loading all 4.67M at once.
    """
    df = _load_challenge_df()
    precomputed = _load_precomputed()

    # Build analyzed lookup
    analyzed_map = {}
    for r in precomputed:
        lid = str(r.get("location_id", ""))
        analyzed_map[lid] = r

    # Spatial filter on the full dataset
    mask = (
        (df["latitude"] >= lat_min) & (df["latitude"] <= lat_max) &
        (df["longitude"] >= lon_min) & (df["longitude"] <= lon_max)
    )
    visible = df[mask]

    rows = []
    n_analyzed = 0

    # First pass: all analyzed points in view (always include all of them)
    visible_lids = set(visible["location_id"].astype(str))
    for lid, am in analyzed_map.items():
        lat = am.get("lat") or am.get("latitude")
        lon = am.get("lon") or am.get("longitude")
        if lat is None or lon is None:
            continue
        lat, lon = float(lat), float(lon)
        if lat_min <= lat <= lat_max and lon_min <= lon <= lon_max:
            n_analyzed += 1
            rows.append({
                "i": lid,
                "a": round(lat, 5),
                "o": round(lon, 5),
                "z": 1,
                "t": str(am.get("risk_tier", "low")),
                "f": bool(am.get("feasible", True)),
                "s": round(float(am.get("risk_score", 0)), 1),
            })

    # Second pass: unanalyzed points (sample if too many)
    analyzed_ids = set(analyzed_map.keys())
    unanalyzed = visible[~visible["location_id"].astype(str).isin(analyzed_ids)]
    if len(unanalyzed) > VIEWPORT_MAX_POINTS:
        unanalyzed = unanalyzed.sample(VIEWPORT_MAX_POINTS, random_state=42)
    for _, r in unanalyzed.iterrows():
        rows.append({
            "i": str(r["location_id"]),
            "a": round(float(r["latitude"]), 5),
            "o": round(float(r["longitude"]), 5),
            "z": 0,
        })

    return JSONResponse(content={
        "points": rows,
        "n_total_in_view": int(mask.sum()),
        "n_analyzed": n_analyzed,
        "n_unanalyzed_shown": len(unanalyzed),
        "truncated": len(visible) - n_analyzed > VIEWPORT_MAX_POINTS,
    })


@app.get("/api/analyzed_points")
async def analyzed_points_endpoint():
    """Return ALL analyzed points (lightweight) — used at all zoom levels."""
    precomputed = _load_precomputed()
    rows = []
    for r in precomputed:
        lat = r.get("lat") or r.get("latitude")
        lon = r.get("lon") or r.get("longitude")
        if lat is None or lon is None:
            continue
        rows.append({
            "i": str(r.get("location_id", "")),
            "a": round(float(lat), 5),
            "o": round(float(lon), 5),
            "t": str(r.get("risk_tier", "low")),
            "f": bool(r.get("feasible", True)),
            "s": round(float(r.get("risk_score", 0)), 1),
        })
    return JSONResponse(content=rows)


# ---------------------------------------------------------------------------
# Block-group-level GeoJSON for mid-zoom choropleth
# ---------------------------------------------------------------------------

_bg_geojson_cache: dict | None = None

@app.get("/api/blockgroup_geojson")
async def blockgroup_geojson():
    """Return NC Census Block Group boundaries with pass-rate data for choropleth."""
    global _bg_geojson_cache
    if _bg_geojson_cache is not None:
        return JSONResponse(content=_bg_geojson_cache)

    bd = ROOT / "data" / "boundaries"
    bd.mkdir(parents=True, exist_ok=True)
    fp = bd / "nc_block_groups.geojson"
    if not fp.exists():
        # Auto-download and convert from TIGER/Line
        logger.info("[blockgroup_geojson] Downloading NC block group boundaries…")
        try:
            import urllib.request, zipfile, tempfile
            url = "https://www2.census.gov/geo/tiger/TIGER2023/BG/tl_2023_37_bg.zip"
            zip_path = bd / "tl_2023_37_bg.zip"
            urllib.request.urlretrieve(url, zip_path)
            import geopandas as gpd
            gdf = gpd.read_file(f"zip://{zip_path}")
            gdf["geometry"] = gdf["geometry"].simplify(0.0005, preserve_topology=True)
            if gdf.crs and gdf.crs.to_epsg() != 4326:
                gdf = gdf.to_crs(epsg=4326)
            gdf.to_file(fp, driver="GeoJSON")
            logger.info(f"[blockgroup_geojson] Saved {len(gdf)} block groups to {fp}")
        except Exception as exc:
            logger.error(f"[blockgroup_geojson] Download failed: {exc}")
            return JSONResponse(content={"type": "FeatureCollection", "features": []})

    full = json.loads(fp.read_text())

    # Load block group summary
    bg_csv = OUT_DIR / "zonal" / "block_group_summary.csv"
    summary: dict[str, dict] = {}
    if bg_csv.exists():
        bdf = pd.read_csv(bg_csv, dtype={"geoid_bg": str})
        for _, row in bdf.iterrows():
            gid = str(row["geoid_bg"])
            summary[gid] = {
                "mean_risk":     round(float(row.get("mean_risk", 0)), 1),
                "pct_feasible":  round(float(row.get("pct_feasible", 0)), 1),
                "pct_critical":  round(float(row.get("pct_critical", 0)), 1),
                "n_points":      int(row.get("n_points", 0)),
                "dominant_mode": str(row.get("dominant_mode", "—")),
            }

    # Attach stats to features
    for feat in full.get("features", []):
        gid = feat.get("properties", {}).get("GEOID", "")
        if gid in summary:
            feat["properties"].update(summary[gid])
            feat["properties"]["has_data"] = True
        else:
            feat["properties"]["has_data"] = False
            feat["properties"]["mean_risk"] = None

    _bg_geojson_cache = full
    n_with = sum(1 for f in full["features"] if f.get("properties", {}).get("has_data"))
    logger.info(f"[blockgroup_geojson] Served {len(full['features'])} block groups ({n_with} with data)")
    return JSONResponse(content=full)


_county_geojson_cache: dict | None = None


@app.get("/api/county_geojson")
async def county_geojson():
    """Return NC county boundaries as GeoJSON with risk summary data for choropleth overlay."""
    global _county_geojson_cache
    if _county_geojson_cache is not None:
        return JSONResponse(content=_county_geojson_cache)

    import urllib.request
    bd = ROOT / "data" / "boundaries"
    bd.mkdir(parents=True, exist_ok=True)
    fp = bd / "us_counties_fips.geojson"
    if not fp.exists():
        url = "https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json"
        with urllib.request.urlopen(url, timeout=60) as r:
            fp.write_bytes(r.read())

    full = json.loads(fp.read_text())
    nc_features = [f for f in full["features"] if str(f.get("id", "")).startswith("37")]

    # Load county summary from zonal output
    county_csv = OUT_DIR / "zonal" / "county_summary.csv"
    summary = {}
    if county_csv.exists():
        cdf = pd.read_csv(county_csv, dtype={"county_fips": str})
        for _, row in cdf.iterrows():
            fips = str(row["county_fips"]).zfill(5)
            summary[fips] = {
                "mean_risk": round(float(row.get("mean_risk", 0)), 1),
                "pct_feasible": round(float(row.get("pct_feasible", 0)), 1),
                "pct_critical": round(float(row.get("pct_critical", 0)), 1),
                "n_points": int(row.get("n_points", 0)),
                "dominant_mode": str(row.get("dominant_mode", "—")),
            }

    # Attach summary data to each feature's properties
    for feat in nc_features:
        fips = str(feat.get("id", ""))
        if fips in summary:
            feat["properties"].update(summary[fips])
        else:
            feat["properties"]["mean_risk"] = None

    result = {"type": "FeatureCollection", "features": nc_features}
    _county_geojson_cache = result
    logger.info(f"[api/county_geojson] Served {len(nc_features)} counties")
    return JSONResponse(content=result)


@app.get("/outputs/{path:path}")
async def serve_output(path: str):
    """Serve files from the outputs/ directory."""
    fp = OUT_DIR / path
    if not fp.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(str(fp))
