"""
app.py — FastAPI web application for LEO satellite risk analysis.

Provides a local interactive map with:
  • Esri World Imagery satellite tile background (via Leaflet.js)
  • Pre-computed risk results as clickable markers (popup with 5-panel PNG)
  • Click-anywhere → nearest DATA_CHALLENGE_50 point lookup → on-demand analysis
  • Leaflet.Draw rectangle → AOI batch analysis (100-point confirmation gate)

Usage:
    conda run -n cs378 uvicorn app:app --reload --port 8000
    # Then open http://localhost:8000 in a browser

Design:
    - All analysis runs synchronously in-process (simple, no task queue)
    - Pre-computed results served from challenge50 + nc_test JSON files
    - Nearest-point lookup uses vectorised numpy distance (no spatial index needed
      for <5M points once loaded; first request cold-loads the CSV in ~5s)
    - PNGs are generated by _plot_point() from main.py (same as CLI)
    - Structured for future deployment: replace localhost uvicorn with gunicorn,
      add auth middleware, swap local PNG serve with S3 presigned URLs

Endpoints:
    GET  /                        — interactive map HTML
    GET  /api/precomputed         — all pre-computed results (JSON)
    POST /api/analyze             — single-point on-demand analysis
    POST /api/analyze_bbox        — batch analysis for a drawn bounding box
    GET  /outputs/{path:path}     — serve PNG / JSON files from outputs/
"""

from __future__ import annotations

import base64
import io
import json
import logging
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
ROOT     = Path(__file__).parent
SRC_DIR  = ROOT / "src"
OUT_DIR  = ROOT / "outputs"
TMPL_DIR = ROOT / "templates"

sys.path.insert(0, str(SRC_DIR))

from feasibility import analyze_location
import main as _main_mod   # for _plot_point, _save_json

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------
app = FastAPI(title="LEO Risk Analysis", version="1.0.0")
app.mount("/outputs", StaticFiles(directory=str(OUT_DIR)), name="outputs")
templates = Jinja2Templates(directory=str(TMPL_DIR))

# ---------------------------------------------------------------------------
# In-memory state (loaded once on first use)
# ---------------------------------------------------------------------------
_challenge_df: pd.DataFrame | None = None   # 4.67M NC addresses (lazy)
_precomputed:  list[dict]  | None = None    # challenge50 + nc_test results

AOI_CONFIRMATION_THRESHOLD = 100   # Points above this require explicit confirm


def _load_challenge_df() -> pd.DataFrame:
    global _challenge_df
    if _challenge_df is None:
        csv = ROOT / "DATA_CHALLENGE_50.csv"
        logger.info(f"Loading {csv.name} …")
        _challenge_df = pd.read_csv(csv, usecols=["location_id", "latitude", "longitude"],
                                    dtype={"location_id": str})
        logger.info(f"Loaded {len(_challenge_df):,} addresses")
    return _challenge_df


def _load_precomputed() -> list[dict]:
    global _precomputed
    if _precomputed is not None:
        return _precomputed

    rows: list[dict] = []

    # Challenge-50 results
    c50_csv = OUT_DIR / "challenge50" / "challenge50_results.csv"
    if c50_csv.exists():
        df = pd.read_csv(c50_csv)
        for col in ("risk_score", "slope_deg", "canopy_max_m", "building_count"):
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)
        if "feasible" in df.columns:
            df["feasible"] = (df["feasible"].astype(str).str.lower()
                              .map({"true": True, "false": False, "1": True, "0": False})
                              .fillna(True))
        for r in df.to_dict("records"):
            r["_source"] = "challenge50"
            rows.append(r)

    # NC test set (per-point JSONs)
    nc_dir = OUT_DIR / "nc_test"
    for jf in sorted(nc_dir.glob("point_*.json")):
        try:
            d = json.loads(jf.read_text())
            rk = d.get("risk", {})
            cl = d.get("classification", {})
            rows.append({
                "location_id":    jf.stem.replace("point_", ""),
                "lat":            d.get("lat"),
                "lon":            d.get("lon"),
                "latitude":       d.get("lat"),
                "longitude":      d.get("lon"),
                "feasible":       d.get("feasible", True),
                "risk_score":     rk.get("risk_score", 0),
                "risk_tier":      rk.get("risk_tier", "low"),
                "dominant":       cl.get("dominant", "clear"),
                "slope_deg":      d.get("slope_deg", 0),
                "canopy_max_m":   d.get("canopy_max_m", 0),
                "building_count": d.get("building_count", 0),
                "warnings":       "; ".join(d.get("warnings", [])),
                "_source":        "nc_test",
            })
        except Exception:
            pass

    # Full batch results (if available)
    batch_csv = OUT_DIR / "batch" / "batch_results.csv"
    if batch_csv.exists():
        bdf = pd.read_csv(batch_csv)
        if "error" in bdf.columns:
            bdf = bdf[bdf["error"].isna()]
        for col in ("risk_score", "slope_deg", "canopy_max_m", "building_count"):
            if col in bdf.columns:
                bdf[col] = pd.to_numeric(bdf[col], errors="coerce").fillna(0)
        if "feasible" in bdf.columns:
            bdf["feasible"] = (bdf["feasible"].astype(str).str.lower()
                               .map({"true": True, "false": False}).fillna(True))
        for r in bdf.to_dict("records"):
            r["_source"] = "batch"
            rows.append(r)

    _precomputed = rows
    logger.info(f"Loaded {len(rows)} pre-computed results")
    return _precomputed


# ---------------------------------------------------------------------------
# Request/response models
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    lat: float
    lon: float
    location_id: str = "on-demand"
    run_search:  bool = True


class BboxRequest(BaseModel):
    lat_min: float
    lat_max: float
    lon_min: float
    lon_max: float
    confirmed: bool = False   # True = user already clicked "Run anyway" for >100 pts


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _nearest_challenge_point(lat: float, lon: float) -> dict | None:
    """Return the nearest DATA_CHALLENGE_50 point to (lat, lon)."""
    df = _load_challenge_df()
    dlat = df["latitude"].values  - lat
    dlon = df["longitude"].values - lon
    dist = dlat**2 + dlon**2
    idx  = int(np.argmin(dist))
    row  = df.iloc[idx]
    return {
        "location_id": str(row["location_id"]),
        "lat":         float(row["latitude"]),
        "lon":         float(row["longitude"]),
        "dist_m":      float(np.sqrt(dist[idx]) * 111_320),
    }


def _png_b64(result: dict, location_id: str) -> str:
    """Generate a 5-panel PNG for result and return as base64 string."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    result["label"] = location_id
    buf = io.BytesIO()
    try:
        fig_path = OUT_DIR / "reports" / location_id / f"{location_id}.png"
        fig_path.parent.mkdir(parents=True, exist_ok=True)
        _main_mod._plot_point(result, fig_path)
        png_bytes = fig_path.read_bytes()
    except Exception as exc:
        logger.warning(f"Plot failed: {exc}")
        return ""
    return base64.b64encode(png_bytes).decode()


def _result_to_api(result: dict, location_id: str, source: str = "on-demand") -> dict:
    """Strip numpy arrays and add API-friendly fields."""
    rk  = result.get("risk", {})
    cl  = result.get("classification", {})
    bn  = result.get("best_nearby") or {}
    imp = bn.get("improvement") or {}
    return {
        "location_id":    location_id,
        "lat":            result["lat"],
        "lon":            result["lon"],
        "feasible":       result["feasible"],
        "failure_mode":   result.get("failure_mode", ""),
        "risk_score":     rk.get("risk_score", 0),
        "risk_tier":      rk.get("risk_tier", "low"),
        "dominant":       cl.get("dominant", "clear"),
        "slope_deg":      result.get("slope_deg", 0),
        "canopy_max_m":   result.get("canopy_max_m", 0),
        "building_count": result.get("building_count", 0),
        "warnings":       "; ".join(result.get("warnings", [])),
        "elapsed_s":      result.get("elapsed_s", 0),
        "best_nearby": {
            "lat":        bn.get("best", {}).get("lat") if bn.get("best") else None,
            "lon":        bn.get("best", {}).get("lon") if bn.get("best") else None,
            "risk_score": bn.get("best", {}).get("risk_score") if bn.get("best") else None,
            "distance_m": imp.get("distance_m"),
            "risk_delta": imp.get("risk_delta"),
            "feasible_gained": imp.get("feasible_gained"),
        } if bn else None,
        "_source":        source,
        "png_url":        f"/outputs/reports/{location_id}/{location_id}.png",
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    precomputed = _load_precomputed()
    return templates.TemplateResponse("map.html", {
        "request":     request,
        "n_precomputed": len(precomputed),
    })


@app.get("/api/precomputed")
async def get_precomputed():
    rows = _load_precomputed()
    # Ensure lat/lon present from either column naming convention
    out = []
    for r in rows:
        lat = r.get("lat") or r.get("latitude")
        lon = r.get("lon") or r.get("longitude")
        if lat is None or lon is None:
            continue
        out.append({
            "location_id":    str(r.get("location_id", "")),
            "lat":            float(lat),
            "lon":            float(lon),
            "feasible":       bool(r.get("feasible", True)),
            "risk_score":     float(r.get("risk_score", 0)),
            "risk_tier":      str(r.get("risk_tier", "low")),
            "dominant":       str(r.get("dominant", "clear")),
            "slope_deg":      float(r.get("slope_deg", 0)),
            "canopy_max_m":   float(r.get("canopy_max_m", 0)),
            "building_count": int(r.get("building_count", 0)),
            "warnings":       str(r.get("warnings", "") or ""),
            "_source":        str(r.get("_source", "")),
            "png_url":        f"/outputs/reports/{r.get('location_id', '')}/{r.get('location_id', '')}.png",
        })
    return JSONResponse(content=out)


@app.post("/api/analyze")
async def analyze(req: AnalyzeRequest):
    """
    On-demand single-point analysis.

    Typically called after a map click: the frontend first looks up the nearest
    DATA_CHALLENGE_50 point via /api/nearest and passes it here.
    """
    t0 = time.time()
    logger.info(f"[api/analyze] lat={req.lat:.5f} lon={req.lon:.5f} id={req.location_id}")
    try:
        result = analyze_location(req.lat, req.lon, run_local_search=req.run_search)
    except Exception as exc:
        logger.error(f"[api/analyze] failed: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))

    # Save JSON
    json_path = OUT_DIR / "reports" / req.location_id / f"{req.location_id}.json"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    _main_mod._save_json(result, json_path)

    # Generate PNG
    _png_b64(result, req.location_id)

    api_result = _result_to_api(result, req.location_id)
    api_result["total_elapsed_s"] = round(time.time() - t0, 1)

    # Invalidate precomputed cache so new result appears immediately
    global _precomputed
    _precomputed = None

    return JSONResponse(content=api_result)


@app.get("/api/nearest")
async def nearest(lat: float, lon: float):
    """Return the nearest DATA_CHALLENGE_50 point to (lat, lon)."""
    pt = _nearest_challenge_point(lat, lon)
    if pt is None:
        raise HTTPException(status_code=404, detail="Dataset not available")
    return JSONResponse(content=pt)


@app.post("/api/analyze_bbox")
async def analyze_bbox(req: BboxRequest):
    """
    Batch analysis for an AOI bounding box drawn on the map.

    Safety gate: if the bbox contains > AOI_CONFIRMATION_THRESHOLD points and
    confirmed=False, return a 202 with the point count so the frontend can show
    a confirmation dialog before re-submitting with confirmed=True.
    """
    df = _load_challenge_df()
    mask = (
        (df["latitude"]  >= req.lat_min) & (df["latitude"]  <= req.lat_max) &
        (df["longitude"] >= req.lon_min) & (df["longitude"] <= req.lon_max)
    )
    subset = df[mask].copy()
    n = len(subset)

    if n == 0:
        return JSONResponse(content={"status": "empty", "n_points": 0, "results": []})

    if n > AOI_CONFIRMATION_THRESHOLD and not req.confirmed:
        return JSONResponse(
            status_code=202,
            content={
                "status":    "confirmation_required",
                "n_points":  n,
                "threshold": AOI_CONFIRMATION_THRESHOLD,
                "message":   (
                    f"This AOI contains {n:,} points, which would take "
                    f"~{n * 30 // 60} minutes to analyse. "
                    f"Re-submit with confirmed=true to proceed."
                ),
            },
        )

    # Cap to threshold even with confirmation (user confirmed they want the run)
    if n > AOI_CONFIRMATION_THRESHOLD:
        subset = subset.sample(AOI_CONFIRMATION_THRESHOLD, random_state=42)
        logger.info(f"[api/analyze_bbox] Sampled {AOI_CONFIRMATION_THRESHOLD} of {n} points")
        n = AOI_CONFIRMATION_THRESHOLD

    logger.info(f"[api/analyze_bbox] Running {n} points …")
    results_out = []
    errors      = []
    for _, row in subset.iterrows():
        lid = str(row["location_id"])
        try:
            res = analyze_location(float(row["latitude"]), float(row["longitude"]),
                                   run_local_search=False)
            json_path = OUT_DIR / "reports" / lid / f"{lid}.json"
            json_path.parent.mkdir(parents=True, exist_ok=True)
            _main_mod._save_json(res, json_path)
            _png_b64(res, lid)
            results_out.append(_result_to_api(res, lid, source="aoi_batch"))
        except Exception as exc:
            errors.append({"location_id": lid, "error": str(exc)})

    # Invalidate precomputed cache
    global _precomputed
    _precomputed = None

    return JSONResponse(content={
        "status":   "complete",
        "n_points": n,
        "results":  results_out,
        "errors":   errors,
    })


@app.get("/outputs/{path:path}")
async def serve_output(path: str):
    """Serve files from the outputs/ directory."""
    fp = OUT_DIR / path
    if not fp.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(str(fp))
